### ISSUE TITLE
Lambda layer with multiple inputs?

### ISSUE THREAD

**Issue by shamangary** [hollance/CoreML-Custom-Layers#1]
Hi. Thank you for the useful project. I encounter an issue when lambda layer receives multiple inputs.
```
# This is a custom activation function.
def swish(x,s1):
    return K.sigmoid(x)*x

def merge(x):
    return x[0]+x[1]

# Create a silly model that has our custom activation function as a new layer.
def create_model():
    a = 3
    inp = Input(shape=(256, 256, 3))
    x = Conv2D(6, (3, 3), padding="same")(inp)
    #x = Activation(swish)(x)                   # doesn't work! :-(
    x = Lambda(swish, arguments={'s1':a})(x)
    x = GlobalAveragePooling2D()(x)
    x0 = Dense(10, activation="softmax")(x)
    x1 = Dense(10, activation="softmax")(x0)
    x = Lambda(merge)([x0,x1])
    return Model(inp, x)
```

There will be an error.
```
Traceback (most recent call last):
  File "test.py", line 98, in <module>
    custom_conversion_functions={ "Lambda": convert_lambda })
  File "/home/shamangary/anaconda3/envs/new/lib/python3.5/site-packages/coremltools/converters/keras/_keras_converter.py", line 745, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/home/shamangary/anaconda3/envs/new/lib/python3.5/site-packages/coremltools/converters/keras/_keras_converter.py", line 543, in convertToSpec
    custom_objects=custom_objects)
  File "/home/shamangary/anaconda3/envs/new/lib/python3.5/site-packages/coremltools/converters/keras/_keras2_converter.py", line 191, in _convert
    graph.build()
  File "/home/shamangary/anaconda3/envs/new/lib/python3.5/site-packages/coremltools/converters/keras/_topology2.py", line 643, in build
    successors = self.edge_map[layer]
KeyError: 'lambda_2'
```
I was trying much more complex merging function other than just addition.
Do you know how to resolve this? Thank you!

**Comment by hollance** [comment]
I haven't tried using multiple inputs. Maybe that's a question that's better asked on the coremltools GitHub page.

**Comment by shamangary** [comment]
I ask the team also. Thanks again.

**Comment by shamangary** [comment]
https://github.com/apple/coremltools/issues/188
I have test their solution. It works like a charm :).
Thank you for your blog post again.
